#include <slib/extensions.h>

#if defined ( _WIN32 )
	#define GETEXTENSIONADDRESS(address) wglGetProcAddress( address )
#endif

#if defined ( __linux__ ) || defined ( __GLIBC__ ) || defined ( __GNU__ )
	#include <GL/glx.h>
	#define GETEXTENSIONADDRESS(address) glXGetProcAddress( (const GLubyte * )address )
#endif

namespace slib {

	void initExtensions( ) {
		// shaders
		glCreateShader = (PFNGLCREATESHADERPROC)GETEXTENSIONADDRESS( "glCreateShader" );
		glShaderSource = (PFNGLSHADERSOURCEPROC)GETEXTENSIONADDRESS( "glShaderSource" );
		glCompileShader = (PFNGLCOMPILESHADERPROC)GETEXTENSIONADDRESS( "glCompileShader" );
		glDetachShader = (PFNGLDETACHSHADERPROC)GETEXTENSIONADDRESS( "glDetachShader" );
		glDeleteShader = (PFNGLDELETESHADERPROC)GETEXTENSIONADDRESS( "glDeleteShader" );
		glCreateProgram = (PFNGLCREATEPROGRAMPROC)GETEXTENSIONADDRESS( "glCreateProgram" );
		glAttachShader = (PFNGLATTACHSHADERPROC)GETEXTENSIONADDRESS( "glAttachShader" );
		glLinkProgram = (PFNGLLINKPROGRAMPROC)GETEXTENSIONADDRESS( "glLinkProgram" );
		glUseProgram = (PFNGLUSEPROGRAMPROC)GETEXTENSIONADDRESS( "glUseProgram" );
		glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)GETEXTENSIONADDRESS( "glBindAttribLocation" );
		glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)GETEXTENSIONADDRESS( "glGetUniformLocation" );
		glUniform1i = (PFNGLUNIFORM1IPROC)GETEXTENSIONADDRESS( "glUniform1i" );
		glUniform1f = (PFNGLUNIFORM1FPROC)GETEXTENSIONADDRESS( "glUniform1f" );
		glUniform2f = (PFNGLUNIFORM2FPROC)GETEXTENSIONADDRESS( "glUniform2f" );
		glUniform3f = (PFNGLUNIFORM3FPROC)GETEXTENSIONADDRESS( "glUniform3f" );
		glUniform4f = (PFNGLUNIFORM4FPROC)GETEXTENSIONADDRESS( "glUniform4f" );
		glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)GETEXTENSIONADDRESS( "glUniformMatrix4fv" );
		glDeleteProgram = (PFNGLDELETEPROGRAMPROC)GETEXTENSIONADDRESS( "glDeleteProgram" );
		glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)GETEXTENSIONADDRESS( "glGetShaderInfoLog" );
		glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)GETEXTENSIONADDRESS( "glGetProgramInfoLog" );
		//glActiveTexture = (PFNGLACTIVETEXTUREPROC)GETEXTENSIONADDRESS( "glActiveTexture" );

		// vao
		glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)GETEXTENSIONADDRESS( "glGenVertexArrays" );
		glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)GETEXTENSIONADDRESS( "glBindVertexArray" );
		glGenBuffers = (PFNGLGENBUFFERSPROC)GETEXTENSIONADDRESS( "glGenBuffers" );
		glBindBuffer = (PFNGLBINDBUFFERPROC)GETEXTENSIONADDRESS( "glBindBuffer" );
		glBufferData = (PFNGLBUFFERDATAPROC)GETEXTENSIONADDRESS( "glBufferData" );
		glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)GETEXTENSIONADDRESS( "glVertexAttribPointer" );
		glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)GETEXTENSIONADDRESS( "glEnableVertexAttribArray" );
		glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)GETEXTENSIONADDRESS( "glDeleteBuffers" );
		glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)GETEXTENSIONADDRESS( "glDeleteVertexArrays" );

		// fbo
		glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)GETEXTENSIONADDRESS( "glGenFramebuffers" );
		glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)GETEXTENSIONADDRESS( "glBindFramebuffer" );
		glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)GETEXTENSIONADDRESS( "glFramebufferTexture2D" );
		glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)GETEXTENSIONADDRESS( "glFramebufferRenderbuffer" );
		glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)GETEXTENSIONADDRESS( "glBlitFramebuffer" );
		glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)GETEXTENSIONADDRESS( "glDeleteFramebuffers" );
		glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)GETEXTENSIONADDRESS( "glGenRenderbuffers" );
		glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)GETEXTENSIONADDRESS( "glBindRenderbuffer" );
		glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)GETEXTENSIONADDRESS( "glRenderbufferStorage" );
		glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)GETEXTENSIONADDRESS( "glDeleteRenderbuffers" );
		glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)GETEXTENSIONADDRESS( "glCheckFramebufferStatus" );
		glDrawBuffers = (PFNGLDRAWBUFFERSPROC)GETEXTENSIONADDRESS( "glDrawBuffers" );
	}

	PFNGLCREATESHADERPROC glCreateShader;
	PFNGLSHADERSOURCEPROC glShaderSource;
	PFNGLCOMPILESHADERPROC glCompileShader;
	PFNGLDETACHSHADERPROC glDetachShader;
	PFNGLDELETESHADERPROC glDeleteShader;
	PFNGLCREATEPROGRAMPROC glCreateProgram;
	PFNGLATTACHSHADERPROC glAttachShader;
	PFNGLLINKPROGRAMPROC glLinkProgram;
	PFNGLUSEPROGRAMPROC glUseProgram;
	PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
	PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
	PFNGLUNIFORM1IPROC glUniform1i;
	PFNGLUNIFORM1FPROC glUniform1f;
	PFNGLUNIFORM2FPROC glUniform2f;
	PFNGLUNIFORM3FPROC glUniform3f;
	PFNGLUNIFORM4FPROC glUniform4f;
	PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
	PFNGLDELETEPROGRAMPROC glDeleteProgram;
	PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
	PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
	//PFNGLACTIVETEXTUREPROC glActiveTexture;

	PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
	PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
	PFNGLGENBUFFERSPROC glGenBuffers;
	PFNGLBINDBUFFERPROC glBindBuffer;
	PFNGLBUFFERDATAPROC glBufferData;
	PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
	PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
	PFNGLDELETEBUFFERSPROC glDeleteBuffers;
	PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;

	PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
	PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
	PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
	PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
	PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
	PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
	PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
	PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
	PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
	PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
	PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
	PFNGLDRAWBUFFERSPROC glDrawBuffers;

}
